name: Test
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Output Stuff
    env:
      CLUSTER_NAME: smoke-test-vm
    outputs:
      env_stuff: ${{ steps.output-stack-id.outputs.stack_id }}
      date: 
    steps:
      - name: Output1
        id: output1
        run: echo "env_stuff=${{ env.CLUSTER_NAME }}" >> $GITHUB_OUTPUT
      - name: Output2
        id: output2
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT 
  job2:
    runs-on: ubuntu-latest
    name: Get Output
    needs: [job1]
    steps:
      - name: get stuff
        id: get-stuff
        run: |
            echo ${{ needs.job1.outputs.env_stuff }}
            echo ${{ needs.job1.outputs.date }}

